server:
  port: 8080

spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB


  redis:
    host: 42.192.178.84
    port: 6379
    password: "209243"
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms

mybatis:
  mapper-locations: classpath:/mapper/*.xml


sms:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 110317
  appSecret: d40f0cf5-70b4-40c9-93a1-4a9ec0484836
  # 7天
  timeOut: 10080
  # 5 min
  #  timeOut: 5
  codeLength: 4


cache:
  # 多少分钟后过期
  expireAfterAccess: 10080




aliyun:
  endPoint: oss-cn-beijing.aliyuncs.com
  urlPrefix: http://cunzhao.oss-cn-beijing.aliyuncs.com/
  accessKeyId: LTAI5t9cBwBHKseLcXkztKrP
  accessKeySecret: I2kDgZFSwAedZdFVvRT5TJZY3RGeWV
  bucketName: cunzhao
  fileHost: files
