spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/cunzhao?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 209243


logging:
  config: classpath:logback-local.xml
server:
  port: 8080
