spring:
  profiles: local
  datasource:
    url: jdbc:mysql://42.192.178.84:3306/cunzhao?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 209243
    driver-class-name: com.mysql.jdbc.Driver



logging:
  config: classpath:logback-local.xml
server:
  port: 8080
