server:
  port: 8080

spring:
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:/mapper/*.xml


sms:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 110317
  appSecret: d40f0cf5-70b4-40c9-93a1-4a9ec0484836
  timeOut: 3
  codeLength: 6